### ISSUE TITLE
一些提问

### ISSUE THREAD

**Issue by LX2035** [qsheeeeen/qdu-robomaster#9]
您好，你这边使用ac6编译器是我第一次看到，我想问下ac6编译器具体如何部署的呢，我这边一直都是失败的，总是会有很多报错，想请教下，非常感谢，另外从您的开源中也看到了很多新思路，非常感谢。

**Comment by qsheeeeen** [comment]
编译器变化带来的影响主要有两点：

- 属性（例如`__packed`）。这个靠升级HAL可以解决，当然自己代码也要适配（例如`__attribute__((packed))`）。
- RTOS移植。FreeRTOS的话你可以看我README和RTOS的文档。我这里主要是FreeRTOS/Source/portable/里找到适合AC6的。

暂时想到这么多，剩下的就要看具体的报错信息了。
